"use client"
import "../globals.css";
import type { Metadata } from "next";
import {  Work_Sans } from "next/font/google";
import { Header } from "@/components/header";
import { useThemeMode } from "@/hooks/useThemeMode";

const primaryFont = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const isDarkMode=useThemeMode(s=>s.isDarkMode)
  return (
    <html lang="en" className={isDarkMode?"dark":''}>
      <body className={primaryFont.className+"overflow-hidden bg-white dark:bg-zinc-800 scrollbar-hide"}>
          <Header />
          <div aria-hidden="true" className="fixed inset-0 h-[200vh] origin-top scale-y-0 bg-gradient-to-b from-gray-100 from-80% to-transparent transition-transform duration-700 dark:scale-y-100 dark:from-zinc-950"></div>
          {children}
      </body>
    </html>
  );
}
